[config]

[templates.dmsgtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/dank-colors.css'

[templates.dmsgtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/dank-colors.css'

[templates.dmsqt5ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.dmsqt6ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.dmskcolorscheme]
input_path = './templates/matugen-kcolorscheme.colors'
output_path = '~/.local/share/color-schemes/DankMatugen.colors'

[templates.dmsdgop]
input_path = './templates/dgop.json'
output_path = '~/.config/dgop/colors.json'

[templates.dmsniri]
input_path = './templates/niri-colors.kdl'
output_path = '~/.config/niri/dankshell-colors.kdl'

[templates.dmsghostty]
input_path = './templates/ghostty-colors.conf'
output_path = '~/.config/ghostty/config-dankcolors'